include: package:flutter_lints/flutter.yaml

rules:
  prefer_typing_uninitialized_varibales : false
  prefer_const_constructors_in_immutables : false
  prefer_const_constructors : false
  avoid_print : false